name: wordduel
description: A real-time word duel game
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^2.30.0

  # Auth (for anonymous or email login)
  firebase_auth: ^4.17.0

  # Firestore for game state sync
  cloud_firestore: ^5.10.0

  # Optional: Realtime Database
  firebase_database: ^10.5.0

  # Optional: Messaging (notifications)
  firebase_messaging: ^15.8.0

  # State management (your choice)
  provider: ^6.1.2

  # UI & Animation (optional)
  flutter_spinkit: ^5.2.0
  animations: ^2.0.8

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
