pluginManagement {
    repositories {
        google()
        mavenCentral()
     //   jcenter()
          // gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'WordDuel_Too_Project'
include ':app'
